version: '3.4'

# You need to start it with the following CLI command:
# docker-compose up --build -d

services:
    sqldata:
        image: 'mcr.microsoft.com/mssql/server:2017-latest'
        environment:
            - SA_PASSWORD=Pass@word
            - ACCEPT_EULA=Y
        ports:
            - '5433:1433'

    blog.api:
        image: 'blog.api:${PLATFORM:-linux}-${TAG:-latest}'
        build:
            context: .
            dockerfile: src/Services/Blog.API/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://0.0.0.0:80
            - ConnectionStrings:DefaultConnection=${BLOG_API_DB:-Server=sqldata;Database=blog_api_db;User Id=sa;Password=Pass@word}
        ports:
            - '5000:80'
        depends_on:
            - sqldata
